INSERT INTO location VALUES
(NULL,'Contemporary Art','Not on View'),
(NULL,'Contemporary Art','Gallery 13, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Not on View'),
(NULL,'Decorative Arts and Design','Gallery 7, Scaife Galleries'),
(NULL,'Photography','Not on View'),
(NULL,'Contemporary Art','Gallery 15, Scaife Galleries'),
(NULL,'Fine Arts','Not on View'),
(NULL,'Heinz Architectural Center','Not on View'),
(NULL,'Decorative Arts and Design','African Art Gallery'),
(NULL,'Contemporary Art','Gallery 16, Scaife Galleries'),
(NULL,'Contemporary Art','Gallery 17, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 18, Bruce Galleries'),
(NULL,'Contemporary Art','Gallery 12, Scaife Galleries'),
(NULL,'Contemporary Art','Museum Grounds'),
(NULL,'Decorative Arts and Design','Museum of Art Lobby'),
(NULL,'Decorative Arts and Design','Gallery 21, Bruce Galleries'),
(NULL,'Decorative Arts and Design','Gallery 20, Bruce Galleries'),
(NULL,'Fine Arts','Gallery 6, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 9, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 19, Bruce Galleries'),
(NULL,'Fine Arts','Gallery 2, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 7, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Hall of Sculpture Balcony'),
(NULL,'Decorative Arts and Design','Gallery 1, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 19, Bruce Galleries'),
(NULL,'Photography','Forum Gallery'),
(NULL,'Decorative Arts and Design','The Charity Randall Gallery'),
(NULL,'Contemporary Art','Museum of Art Lobby'),
(NULL,'Fine Arts','Gallery 3, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 4, Scaife Galleries'),
(NULL,'Contemporary Art','Carnegie Music Hall and Foyer'),
(NULL,'Fine Arts','Gallery 11, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 6, Scaife Galleries'),
(NULL,'Film and Video','Not on View'),
(NULL,'Fine Arts','Gallery 8, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 4, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 20, Bruce Galleries'),
(NULL,'Decorative Arts and Design','Gallery 9, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 3, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 21, Bruce Galleries'),
(NULL,'Fine Arts','Gallery 10, Scaife Galleries'),
(NULL,'Heinz Architectural Center','The Heinz Architectural Center'),
(NULL,'Fine Arts','Grand Staircase'),
(NULL,'Fine Arts','Forum Gallery'),
(NULL,'Contemporary Art','Forum Gallery'),
(NULL,'Contemporary Art','Hall of Sculpture Balcony'),
(NULL,'Contemporary Art','Gallery 14, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 5, Scaife Galleries'),
(NULL,'Fine Arts','Carnegie Music Hall and Foyer'),
(NULL,'Decorative Arts and Design','Gallery 15, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 2, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Gallery 5, Scaife Galleries'),
(NULL,'Decorative Arts and Design','Art before 1300 Gallery'),
(NULL,'Contemporary Art','Gallery 21, Bruce Galleries'),
(NULL,'Decorative Arts and Design','Hall of Architecture'),
(NULL,'Fine Arts','Gallery 12, Scaife Galleries'),
(NULL,'Contemporary Art','Off-site'),
(NULL,'Fine Arts','Museum Grounds'),
(NULL,'Fine Arts','Gallery 1, Scaife Galleries'),
(NULL,'Fine Arts','Gallery 18, Bruce Galleries'),
(NULL,'Decorative Arts and Design','The Heinz Architectural Center'),
(NULL,'Contemporary Art','Gallery 2, Scaife Galleries'),
(NULL,'Fine Arts','Off-site'),
(NULL,'Decorative Arts and Design','Carnegie Music Hall and Foyer'),
(NULL,'Decorative Arts and Design','Gallery 10, Scaife Galleries'),
(NULL,'Contemporary Art','Hall of Sculpture'),
(NULL,'Contemporary Art','Courtyard Entry'),
(NULL,'Unknown','Unknown');
